---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keydb-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app: keydb
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
data:
  keydb.conf: |
      {{- toYaml $.Values.keydbConfig | nindent 8 }}
