---
apiVersion: v1
kind: Service
metadata:
  name: keydb
  namespace: {{ .Release.Namespace }}
  labels:
    app: keydb
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
spec:
  type: {{ if .Values.nodePort.enabled }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - name: tcp-keydb
      port: 6379
      targetPort: 6379
      protocol: TCP
      {{- if .Values.nodePort.enabled }}
      nodePort: 31379
      {{- end }}
  selector:
    app: keydb
